# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_arith_unary_operator <- function(op, x) {
    .Call(`_AltStat_C_arith_unary_operator`, op, x)
}

test <- function(x, y) {
    .Call(`_AltStat_test`, x, y)
}

C_has_ptr <- function(x) {
    .Call(`_AltStat_C_has_ptr`, x)
}

C_binary_arith_operator <- function(op, x, y) {
    .Call(`_AltStat_C_binary_arith_operator`, op, x, y)
}

